repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: check-json
  - id: check-ast
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: mixed-line-ending
  - id: check-merge-conflict
  - id: trailing-whitespace
  - id: detect-private-key

- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
    name: isort (python)

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']

- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
  - id: flake8

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.961
  hooks:
  - id: mypy
